const defaultProjectsEntry = {
  list: [
    {
      _list: [
        {
          _maxPriority: 10,
          _minPriority: 1,
          _id: 1,
          _projectId: 4,
          _isComplete: true,
          _title: "Foundations Course",
          _description: "",
          _priority: 1,
          _dueDate: "",
          _creationDatetime: "2020-12-12T13:51:44.871Z",
        },
        {
          _maxPriority: 10,
          _minPriority: 1,
          _id: 2,
          _projectId: 4,
          _isComplete: false,
          _title: "JS Course",
          _description: "",
          _priority: 1,
          _dueDate: "",
          _creationDatetime: "2020-12-12T13:51:54.421Z",
        },
        {
          _maxPriority: 10,
          _minPriority: 1,
          _id: 5,
          _projectId: 4,
          _isComplete: false,
          _title: "HTML/CSS",
          _description: "",
          _priority: 9,
          _dueDate: "",
          _creationDatetime: "2020-12-12T13:52:47.566Z",
        },
        {
          _maxPriority: 10,
          _minPriority: 1,
          _id: 4,
          _projectId: 4,
          _isComplete: false,
          _title: "Node",
          _description: "",
          _priority: 10,
          _dueDate: "",
          _creationDatetime: "2020-12-12T13:52:19.756Z",
        },
      ],
      _listSort: "highestPriorityFirst",
      _maxPriority: 10,
      _minPriority: 1,
      _minDueDate: "2020-01-01T00:00:00.000Z",
      _id: 4,
      _title: "The Odin Project",
      _isComplete: false,
      _description: "",
      _priority: 1,
      _dueDate: "",
      _creationDatetime: "2020-12-12T13:51:28.785Z",
      _toDoIDCounter: 6,
      settings: {
        view: "project",
        toDoViewSortPref: "dueDateEarliestFirst",
        projectViewProjectSortPref: "dueDateEarliestFirst",
        projectViewToDoSortPref: "dueDateEarliestFirst",
      },
    },
    {
      _list: [],
      _listSort: "highestPriorityFirst",
      _maxPriority: 10,
      _minPriority: 1,
      _minDueDate: "2020-01-01T00:00:00.000Z",
      _id: 0,
      _title: "Other",
      _isComplete: false,
      _description: "",
      _priority: 10,
      _dueDate: "",
      _creationDatetime: "2020-12-04T17:07:59.291Z",
      _toDoIDCounter: 2,
      settings: {
        view: "project",
        toDoViewSortPref: "dueDateEarliestFirst",
        projectViewProjectSortPref: "dueDateEarliestFirst",
        projectViewToDoSortPref: "dueDateEarliestFirst",
      },
    },
  ],
  toDoIDCounter: 5,
};

const defaultSettingsEntry = {
  view: "project",
  toDoViewSortPref: "dueDateEarliestFirst",
  projectViewProjectSortPref: "dueDateEarliestFirst",
  projectViewToDoSortPref: "dueDateEarliestFirst",
};

export { defaultProjectsEntry, defaultSettingsEntry };
